export const copy = {
  appTitleByAsset: (asset: string) => `AHR999 指標`,
  appSubtitle: "來源：幣安現貨 API",
  symbolLabel: "交易對",
  symbolSearchPlaceholder: "搜尋交易對...",
  openSymbolSelector: "開啟交易對選單",
  fixedIntervalLabel: "1D",
  loadingPairsTitle: "載入交易對中",
  loadingPairsDescription: "正在向幣安取得可交易商品清單。",
  loadingDataTitle: "載入歷史資料中",
  loadingDataDescriptionByAsset: (asset: string) =>
    `正在同步 ${asset} 價格、200 日定投成本與 AHR999 指標。`,
  errorTitle: "資料讀取失敗",
  errorDescription: "目前無法取得幣安公開資料，請稍後重試。",
  emptyTitle: "查無可顯示資料",
  emptyDescription: "請切換交易對或稍後再試。",
  retryButton: "重試",
  refreshingData: "每秒同步中",
  loadMoreHint: "向左拖曳可載入更早歷史資料",
  loadingMore: "載入更多歷史資料中...",
  legendDcaCost: "200日定投成本",
  legendPriceByAsset: (asset: string) => `${asset}價格`,
  legendAhrIndexByAsset: (asset: string) => `${asset} AHR999 指標`,
  legendBottomLine: "抄底線",
  legendDcaLine: "定投線",
  legendOverheatLine: "動能線",
  valuationModeBitcoin: "估值模型：BTC 幣齡估值",
  valuationModePowerLawByAsset: (asset: string) => `估值模型：${asset} 幣價指數擬合線（代理）`,
  starPairBySymbol: (symbol: string) => `將 ${symbol} 設為星號`,
  unstarPairBySymbol: (symbol: string) => `取消 ${symbol} 星號`,
  currentPriceLine: "現價",
  currentAhrLine: "目前值"
} as const;
