export const copy = {
  appTitle: "Crypto K 線與 AHR999",
  appSubtitle: "可切換交易對，上半部 K 線，下半部 AHR999",
  fixedIntervalLabel: "週期：1 日（固定）",
  symbolLabel: "交易對",
  symbolSearchPlaceholder: "搜尋交易對...",
  openSymbolSelector: "開啟交易對選單",
  intervalLabel: "週期",
  intervalSearchPlaceholder: "搜尋週期...",
  openIntervalSelector: "開啟週期選單",
  loadingPairsTitle: "載入交易對中",
  loadingPairsDescription: "正在向幣安取得可交易商品清單。",
  loadingDataTitle: "載入歷史 K 線中",
  loadingDataDescription: "正在同步 K 線與 AHR999 指標資料。",
  errorTitle: "資料讀取失敗",
  errorDescription: "目前無法取得幣安公開資料，請稍後重試。",
  emptyTitle: "查無可顯示資料",
  emptyDescription: "請切換交易對或稍後再試。",
  retryButton: "重新整理",
  refreshingData: "更新資料中...",
  loadMoreHint: "向左拖曳可載入更早歷史資料",
  loadingMore: "載入更多歷史資料中...",
  latestClose: "最新收盤",
  latestAhr: "最新 AHR999",
  metricOpen: "開",
  metricHigh: "高",
  metricLow: "低",
  metricClose: "收",
  hoverPriceLabel: "K 線",
  hoverAhrLabel: "AHR999",
  currentPriceLine: "現價",
  currentAhrLine: "目前值",
  ahrBottomLine: "抄底線 0.45",
  ahrDcaLine: "定投線 1.2",
  ahrFormulaNotice:
    "AHR999 =（價格 / 200 日定投成本）×（價格 / 指數增長估值），其中估值 = 10^[5.84 × log10(幣齡) - 17.01]。"
} as const;
